# RE6111068 黃子軒 HW1

## Part 2

In [1]:
import pandas as pd
import numpy as np

In [2]:
data1=pd.read_csv("data.csv")
crx=pd.read_csv("crx.csv")

In [3]:
data1

,ID,Diagnosis,3,4,5,6,7,8,9,10,...,23,24,25,26,27,28,29,30,31,Unnamed: 31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [4]:
data1.replace("?",np.nan)
data1.dropna()

,ID,Diagnosis,3,4,5,6,7,8,9,10,...,23,24,25,26,27,28,29,30,31,Unnamed: 31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [5]:
label1=data1["Diagnosis"]
data1=data1.drop(columns=['Diagnosis','ID'])

In [6]:
for i in range(0,len(label1)):
    if(label1[i]=='M'):
        label1[i]=1
    else:
        label1[i]=-1

C:\Users\andre\AppData\Local\Temp\ipykernel_4500\2993124554.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  label1[i]=1
C:\Users\andre\AppData\Local\Temp\ipykernel_4500\2993124554.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  label1[i]=-1

In [7]:
label_ori=label1
data1=(data1-data1.mean())/data1.std()
data1['beta_0']=[1]*len(data1)
data_ori=data1

In [8]:
import random
def shuffle(df,label):
    temp=list(range(len(df)))
    random.shuffle(temp)
    df=df.iloc[temp,:]
    label=label.iloc[temp]
    return(df,label)

In [9]:
random.seed(6111016)
data1,label1=shuffle(data1,label1)

## Part 2

In [10]:
def updating_rule(beta,row,label):
    judge=0
    count=0
    while judge==0 and count <10:
        score=0
        for i in range(0,len(beta)):
            score=score+beta[i]*row[i]
        if (score>=0 and label==1):
            judge=1
        if (score<0 and label==-1):
            judge=1
        if (score>=0 and label==-1):
            for i in range(0,len(beta)):
                if i == (len(beta)-1):
                    if row[i]>=0:
                        beta[i]=beta[i]-1#if use data(crx) -> 1 ,else ->30
                    else:
                        beta[i]=beta[i]+1#if use data(crx) -> 1 ,else ->30
                else:
                    if row[i]>=0:
                        beta[i]=beta[i]-1
                    else:
                        beta[i]=beta[i]+1
        if (score<0 and label==1):
            for i in range(0,len(beta)):
                if i == (len(beta)-1):
                    if row[i]>=0:
                        beta[i]=beta[i]+1#if use data(crx) -> 1 ,else ->30
                    else:
                        beta[i]=beta[i]-1#if use data(crx) -> 1 ,else ->30
                else:
                    if row[i]>=0:
                        beta[i]=beta[i]+1
                    else:
                        beta[i]=beta[i]-1
        count=count+1
    return beta

In [11]:
beta=[0]*31

In [12]:
for i in range(0,len(label1)):
    beta=updating_rule(beta,data1.iloc[i],label1[i])

In [13]:
def predict_value(beta,row):
    score=0
    for i in range(0,len(beta)):
        score=score+beta[i]*row[i]
        if (score>=0):
            judge=1
        if (score<0):
            judge=-1
    return judge

In [14]:
label_pred=[]
for i in range(0,len(label1)):
    label_pred.append(predict_value(beta,data1.iloc[i]))

In [15]:
from sklearn.metrics import confusion_matrix
confusion_matrix(label_pred,list(label1))

array([[322,  75],
       [ 35, 137]], dtype=int64)

## Part 3

### For hat(beta) = Inv(t(X)X)t(X)Y , we need to add beta_0 into the matrix

In [16]:
normalized_df=data1

In [17]:
np_normalized_df=normalized_df.to_numpy()

In [18]:
np_normalized_df

array([[-0.30569717,  0.00473177, -0.38516156, ..., -0.74636272,
        -1.16579954,  1.        ],
       [-0.45041707, -0.28357088, -0.51644278, ..., -1.07933254,
        -1.59101887,  1.        ],
       [ 1.8111861 ,  1.98099992,  1.74620354, ..., -0.74959543,
        -0.03686437,  1.        ],
       ...,
       [ 1.74024497,  0.86963971,  1.66389556, ...,  1.27408527,
        -0.01471753,  1.        ],
       [ 0.53992108, -0.87877635,  0.56919945, ...,  0.19112515,
         0.40385775,  1.        ],
       [-1.24552523, -1.70183391, -1.2646223 , ...,  0.33013197,
        -0.13486414,  1.        ]])

In [19]:
t_np_df=np_normalized_df.transpose(1,0)

In [20]:
from numpy.linalg import inv
def least_squares(df,label):
    temp_df=np.matmul(df.transpose(1,0),df)
    temp_inv=inv(np.matrix(temp_df))
    output_df=np.matmul(temp_inv,df.transpose(1,0))
    output_df=np.matmul(output_df,label)
    return output_df

In [21]:
least_beta=least_squares(np_normalized_df,label1)
least_beta

array([-1.534878713845798, 0.03910044670157291, 1.1537088631169394,
       0.2237010786801092, 0.002382157751795744, -0.4459546514521419,
       0.22289615199083995, 0.16621842932205455, 0.005631397817998768,
       0.00046967806109653523, 0.241237636592737, -0.0074566007967997085,
       -0.09106537111784656, -0.08399621989566915, 0.09520576506739739,
       0.0023246037734371036, -0.21525486338806799, 0.1304145465490944,
       0.028061697579600805, -0.03781997562456793, 1.8867343561258716,
       0.0880067287864253, -0.16364777943606534, -1.1514941345144694,
       0.02478948192497116, 0.021132900396142074, 0.15905148593371546,
       0.061040352929052695, 0.06889407085610272, 0.15545271731769975,
       -0.25483304042179145], dtype=object)

In [22]:
label_pred_least=[]
for i in range(0,len(label1)):
    label_pred_least.append(predict_value(least_beta,normalized_df.iloc[i]))

In [23]:
confusion_matrix(label_pred_least,list(label1))

array([[355,  18],
       [  2, 194]], dtype=int64)

### Part 4

In [24]:
def vote_perceptron(df,label):
    iter_i=1
    random.seed(iter_i*6111016)
    label_total=[]
    while iter_i<=25:
        shuf_df,shuf_label=shuffle(df,label)
        beta=[0]*31
        for i in range(0,len(shuf_label)):
            beta=updating_rule(beta,shuf_df.iloc[i],shuf_label[i])
        label_pred=[]
        for i in range(0,len(label)):
            label_pred.append(predict_value(beta,df.iloc[i]))
        label_total.append(label_pred)
        iter_i=iter_i+1
    label_total=pd.DataFrame(label_total)
    mean_label=label_total.mean()
    out_label=[]
    for i in range(0,len(mean_label)):
        if(mean_label[i]>=0):
            out_label.append(1)
        else:
            out_label.append(-1)
    return out_label

In [25]:
vote_pred=vote_perceptron(data_ori,label_ori)

In [26]:
confusion_matrix(vote_pred,list(label_ori))

array([[298, 209],
       [ 59,   3]], dtype=int64)

In [27]:
def average_perceptron(df,label):
    iter_i=1
    random.seed(iter_i*6111016)
    beta_total=[]
    while iter_i<=25:
        shuf_df,shuf_label=shuffle(df,label)
        beta=[0]*31
        for i in range(0,len(shuf_label)):
            beta=updating_rule(beta,shuf_df.iloc[i],shuf_label[i])
        beta_total.append(beta)
        iter_i=iter_i+1
    beta_total=pd.DataFrame(beta_total)
    mean_beta=beta_total.mean()
    out_label=[]
    for i in range(0,len(label)):
        out_label.append(predict_value(mean_beta,df.iloc[i]))
    return out_label

In [28]:
average_pred=average_perceptron(data_ori,label_ori)

In [29]:
confusion_matrix(average_pred,list(label_ori))

array([[323, 212],
       [ 34,   0]], dtype=int64)

### Part 5

In [30]:
ini_beta=[0]*31
ini_beta[30]=sum(label_ori)
random.seed(6111016)
ini_beta[random.randint(0,29)]=1

In [31]:
def minimize_linear_classifier(beta,df,label):
    random.seed(999)
    shuf_df,shuf_label=shuffle(df,label)
    dis_ori=np.array(shuf_df).dot(np.array(beta))
    dis_ori=np.absolute(dis_ori)
    dis_ori_sum=sum(dis_ori)/((np.array(beta).dot(np.array(beta)))**0.5)
    for k in range(0,40):
        for i in range(0,len(shuf_df)):
            score=0
            temp_beta=beta
            for j in range(0,len(beta)):
                score=score+beta[j]*shuf_df.iloc[i][j]
            if (score>=0 and shuf_label[i]==-1):
                for g in range(0,len(beta)):
                    if g == (len(beta)-1):
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]-1#if use data(crx) -> 1 ,else ->30
                        else:
                            temp_beta[g]=temp_beta[g]+1#if use data(crx) -> 1 ,else ->30
                    else:
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]-1
                        else:
                            temp_beta[g]=temp_beta[g]+1
                    dis_temp=np.array(shuf_df).dot(np.array(temp_beta))
                    dis_temp=np.absolute(dis_temp)
                    dis_temp_sum=sum(dis_temp)/((np.array(temp_beta).dot(np.array(temp_beta)))**0.5)
                    if(dis_temp_sum<=dis_ori_sum):
                        beta=temp_beta
            if (score<0 and shuf_label[i]==1):
                for g in range(0,len(beta)):
                    if g == (len(beta)-1):
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]+1#if use data(crx) -> 1 ,else ->30
                        else:
                            temp_beta[g]=temp_beta[g]-1#if use data(crx) -> 1 ,else ->30
                    else:
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]+1
                        else:
                            temp_beta[g]=temp_beta[g]-1
                    dis_temp=np.array(shuf_df).dot(np.array(temp_beta))
                    dis_temp=np.absolute(dis_temp)
                    dis_temp_sum=sum(dis_temp)/((np.array(temp_beta).dot(np.array(temp_beta)))**0.5)
                    if(dis_temp_sum<=dis_ori_sum):
                        beta=temp_beta
    return beta

In [32]:
mini_beta = minimize_linear_classifier(ini_beta,data_ori,label_ori)

In [33]:
label_pred_mini=[]
for i in range(0,len(label1)):
    label_pred_mini.append(predict_value(mini_beta,data1.iloc[i]))
confusion_matrix(label_pred_mini,list(label1))

array([[336,  53],
       [ 21, 159]], dtype=int64)

### Part 6

In [34]:
def slack_minimize_linear_classifier(slack_C,beta,df,label):
    random.seed(9999999)
    shuf_df,shuf_label=shuffle(df,label)
    dis_ori=np.array(shuf_df).dot(np.array(beta))
    dis_ori=np.absolute(dis_ori)
    dis_ori_sum=0
    for i in range(0,len(dis_ori)):
        if (dis_ori[i])>slack_C:
            dis_ori_sum=dis_ori_sum+dis_ori[i]
    dis_ori_sum=dis_ori_sum/((np.array(beta).dot(np.array(beta)))**0.5)
    for k in range(0,40):
        for i in range(0,len(shuf_df)):
            score=0
            temp_beta=beta
            for j in range(0,len(beta)):
                score=score+beta[j]*shuf_df.iloc[i][j]
            if (score>=0 and shuf_label[i]==-1):
                for g in range(0,len(beta)):
                    if g == (len(beta)-1):
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]-1#if use data(crx) -> 1 ,else ->30
                        else:
                            temp_beta[g]=temp_beta[g]+1#if use data(crx) -> 1 ,else ->30
                    else:
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]-1
                        else:
                            temp_beta[g]=temp_beta[g]+1
                    dis_temp=np.array(shuf_df).dot(np.array(temp_beta))
                    dis_temp=np.absolute(dis_temp)
                    dis_temp_sum=sum(dis_temp)/((np.array(temp_beta).dot(np.array(temp_beta)))**0.5)
                    if(dis_temp_sum<=dis_ori_sum):
                        beta=temp_beta
            if (score<0 and shuf_label[i]==1):
                for g in range(0,len(beta)):
                    if g == (len(beta)-1):
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]+1#if use data(crx) -> 1 ,else ->30
                        else:
                            temp_beta[g]=temp_beta[g]-1#if use data(crx) -> 1 ,else ->30
                    else:
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]+1
                        else:
                            temp_beta[g]=temp_beta[g]-1
                    dis_temp=np.array(shuf_df).dot(np.array(temp_beta))
                    dis_temp=np.absolute(dis_temp)
                    dis_temp_sum=0
                    for h in range(0,len(dis_temp)):
                        if(dis_temp[h]>slack_C):
                            dis_temp_sum=dis_temp_sum+dis_temp[h]
                    dis_temp_sum=dis_temp_sum/((np.array(temp_beta).dot(np.array(temp_beta)))**0.5)
                    if(dis_temp_sum<=dis_ori_sum):
                        beta=temp_beta
    return beta

In [35]:
slack_beta=slack_minimize_linear_classifier(100,ini_beta,data_ori,label_ori)
label_pred_slack=[]
for i in range(0,len(label1)):
    label_pred_slack.append(predict_value(slack_beta,data1.iloc[i]))
confusion_matrix(label_pred_slack,list(label1))

array([[333,  42],
       [ 24, 170]], dtype=int64)

### Part 7

In [36]:
from sklearn.svm import SVC
model = SVC()
model.fit(data_ori,np.array(label_ori,dtype=int))
predictions = model.predict(data_ori)
confusion_matrix(predictions,np.array(label_ori,dtype=int))

array([[357,   7],
       [  0, 205]], dtype=int64)

In [37]:
label_ori

0       1
1       1
2       1
3       1
4       1
       ..
564     1
565     1
566     1
567     1
568    -1
Name: Diagnosis, Length: 569, dtype: object

In [38]:
crx

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,att11,att12,att13,att14,att15,label
0,b,30.83,0.000,u,g,w,v,1.25,t,t,1,f,g,202,0,+
1,a,58.67,4.460,u,g,q,h,3.04,t,t,6,f,g,43,560,+
2,a,24.5,0.500,u,g,q,h,1.50,t,f,0,f,g,280,824,+
3,b,27.83,1.540,u,g,w,v,3.75,t,t,5,t,g,100,3,+
4,b,20.17,5.625,u,g,w,v,1.71,t,f,0,f,s,120,0,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,b,21.08,10.085,y,p,e,h,1.25,f,f,0,f,g,260,0,-
686,a,22.67,0.750,u,g,c,v,2.00,f,t,2,t,g,200,394,-
687,a,25.25,13.500,y,p,ff,ff,2.00,f,t,1,t,g,200,1,-
688,b,17.92,0.205,u,g,aa,v,0.04,f,f,0,f,g,280,750,-
689,b,35,3.375,u,g,c,h,8.29,f,f,0,t,g,0,0,-

In [39]:
crx=crx.replace("?",np.nan)
crx=crx.dropna()
index = []
for i in range(crx.shape[0]):
    index.append(i)
crx.index = index

In [40]:
crx

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,att11,att12,att13,att14,att15,label
0,b,30.83,0.000,u,g,w,v,1.25,t,t,1,f,g,202,0,+
1,a,58.67,4.460,u,g,q,h,3.04,t,t,6,f,g,43,560,+
2,a,24.5,0.500,u,g,q,h,1.50,t,f,0,f,g,280,824,+
3,b,27.83,1.540,u,g,w,v,3.75,t,t,5,t,g,100,3,+
4,b,20.17,5.625,u,g,w,v,1.71,t,f,0,f,s,120,0,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,b,21.08,10.085,y,p,e,h,1.25,f,f,0,f,g,260,0,-
649,a,22.67,0.750,u,g,c,v,2.00,f,t,2,t,g,200,394,-
650,a,25.25,13.500,y,p,ff,ff,2.00,f,t,1,t,g,200,1,-
651,b,17.92,0.205,u,g,aa,v,0.04,f,f,0,f,g,280,750,-
652,b,35,3.375,u,g,c,h,8.29,f,f,0,t,g,0,0,-

In [41]:
crx['att2']=pd.to_numeric(crx['att2'])
crx['att14']=pd.to_numeric(crx['att14'])

In [42]:
crx

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,att11,att12,att13,att14,att15,label
0,b,30.83,0.000,u,g,w,v,1.25,t,t,1,f,g,202,0,+
1,a,58.67,4.460,u,g,q,h,3.04,t,t,6,f,g,43,560,+
2,a,24.50,0.500,u,g,q,h,1.50,t,f,0,f,g,280,824,+
3,b,27.83,1.540,u,g,w,v,3.75,t,t,5,t,g,100,3,+
4,b,20.17,5.625,u,g,w,v,1.71,t,f,0,f,s,120,0,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,b,21.08,10.085,y,p,e,h,1.25,f,f,0,f,g,260,0,-
649,a,22.67,0.750,u,g,c,v,2.00,f,t,2,t,g,200,394,-
650,a,25.25,13.500,y,p,ff,ff,2.00,f,t,1,t,g,200,1,-
651,b,17.92,0.205,u,g,aa,v,0.04,f,f,0,f,g,280,750,-
652,b,35.00,3.375,u,g,c,h,8.29,f,f,0,t,g,0,0,-

In [43]:
crx_dummy=pd.get_dummies(crx.iloc[:,0:15],drop_first=True)

In [44]:
crx_dummy_label=crx.iloc[:,15]
crx_dummy_label=crx_dummy_label.replace("+",1)
crx_dummy_label=crx_dummy_label.replace("-",-1)
crx_dummy

,att2,att3,att8,att11,att14,att15,att1_b,att4_u,att4_y,att5_gg,...,att7_j,att7_n,att7_o,att7_v,att7_z,att9_t,att10_t,att12_t,att13_p,att13_s
0,30.83,0.000,1.25,1,202,0,1,1,0,0,...,0,0,0,1,0,1,1,0,0,0
1,58.67,4.460,3.04,6,43,560,0,1,0,0,...,0,0,0,0,0,1,1,0,0,0
2,24.50,0.500,1.50,0,280,824,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,27.83,1.540,3.75,5,100,3,1,1,0,0,...,0,0,0,1,0,1,1,1,0,0
4,20.17,5.625,1.71,0,120,0,1,1,0,0,...,0,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,21.08,10.085,1.25,0,260,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
649,22.67,0.750,2.00,2,200,394,0,1,0,0,...,0,0,0,1,0,0,1,1,0,0
650,25.25,13.500,2.00,1,200,1,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
651,17.92,0.205,0.04,0,280,750,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0
652,35.00,3.375,8.29,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0

In [45]:
crx_dummy=(crx_dummy-crx_dummy.mean())/crx_dummy.std()

In [46]:
crx_dummy['beta_0']=[1]*len(crx_dummy)
crx_dummy['beta_0']=pd.to_numeric(crx_dummy['beta_0'])

### crx part2

In [47]:
random.seed(30)
crx_data,crx_label=shuffle(crx_dummy,crx_dummy_label)
beta_crx=[0]*38
for i in range(0,len(crx_label)):
    beta_crx=updating_rule(beta_crx,crx_data.iloc[i],crx_label[i])
label_pred_crx=[]
for i in range(0,len(crx_label)):
    label_pred_crx.append(predict_value(beta_crx,crx_data.iloc[i]))
confusion_matrix(label_pred_crx,list(crx_label))

array([[316, 223],
       [ 41,  73]], dtype=int64)

In [48]:
beta_crx

[-23,
 53,
 7,
 31,
 -1,
 101,
 11,
 11,
 13,
 53,
 13,
 71,
 25,
 51,
 75,
 51,
 85,
 71,
 65,
 69,
 81,
 107,
 65,
 49,
 77,
 55,
 43,
 51,
 95,
 71,
 39,
 71,
 -11,
 29,
 23,
 53,
 -31,
 -77]

In [49]:
crx_data

,att2,att3,att8,att11,att14,att15,att1_b,att4_u,att4_y,att5_gg,...,att7_n,att7_o,att7_v,att7_z,att9_t,att10_t,att12_t,att13_p,att13_s,beta_0
367,0.210857,0.133371,-0.220786,-0.503633,-0.715164,-0.192977,0.671134,-1.798693,1.814113,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,-1.070639,-0.884846,1.077252,-0.055385,-0.296982,1
172,-0.458159,0.762962,-0.246000,-0.503633,-0.120976,-0.164423,-1.487735,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,0.932591,-0.884846,-0.926866,-0.055385,-0.296982,1
180,1.456817,0.730139,3.042224,1.307780,0.003804,0.122065,0.671134,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,-1.182620,-0.111284,0.932591,1.128410,-0.926866,-0.055385,-0.296982,1
638,0.851154,-0.753824,-0.468478,-0.503633,0.354375,-0.147862,-1.487735,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,-1.070639,-0.884846,-0.926866,-0.055385,-0.296982,1
614,1.400221,-0.214744,-0.369104,-0.503633,-0.477489,-0.192596,0.671134,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,-1.182620,-0.111284,-1.070639,-0.884846,-0.926866,-0.055385,-0.296982,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,1.583525,-0.794603,-0.517423,-0.503633,0.354375,-0.170705,-1.487735,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,-1.070639,-0.884846,1.077252,-0.055385,-0.296982,1
30,-0.190384,1.981363,0.829310,0.502708,-0.073441,-0.192977,0.671134,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,0.932591,1.128410,1.077252,-0.055385,-0.296982,1
625,-0.141390,-0.264474,-0.616797,-0.503633,0.211769,-0.192977,0.671134,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,-1.070639,-0.884846,-0.926866,-0.055385,-0.296982,1
296,0.020796,-0.363936,-0.665742,-0.503633,-0.120976,-0.189170,-1.487735,-1.798693,1.814113,-0.055385,...,-0.078447,-0.055385,-1.182620,-0.111284,-1.070639,-0.884846,-0.926866,-0.055385,-0.296982,1
552,0.802160,-0.952747,-0.653876,-0.302365,2.255777,-0.192977,0.671134,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,-1.070639,1.128410,-0.926866,-0.055385,3.362056,1

In [50]:
crx_label[0]

1

In [51]:
crx_dummy

,att2,att3,att8,att11,att14,att15,att1_b,att4_u,att4_y,att5_gg,...,att7_n,att7_o,att7_v,att7_z,att9_t,att10_t,att12_t,att13_p,att13_s,beta_0
0,-0.056918,-0.960704,-0.294945,-0.302365,0.128583,-0.192977,0.671134,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,0.932591,1.128410,-0.926866,-0.055385,-0.296982,1
1,2.294777,-0.073509,0.236036,0.703976,-0.816176,-0.086377,-1.487735,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,-1.182620,-0.111284,0.932591,1.128410,-0.926866,-0.055385,-0.296982,1
2,-0.591625,-0.861243,-0.220786,-0.503633,0.592050,-0.036122,-1.487735,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,-1.182620,-0.111284,0.932591,-0.884846,-0.926866,-0.055385,-0.296982,1
3,-0.310334,-0.654363,0.446648,0.502708,-0.477489,-0.192406,0.671134,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,0.932591,1.128410,1.077252,-0.055385,-0.296982,1
4,-0.957388,0.158236,-0.158492,-0.503633,-0.358651,-0.192977,0.671134,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,0.932591,-0.884846,-0.926866,-0.055385,3.362056,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,-0.880518,1.045432,-0.294945,-0.503633,0.473212,-0.192977,0.671134,-1.798693,1.814113,-0.055385,...,-0.078447,-0.055385,-1.182620,-0.111284,-1.070639,-0.884846,-0.926866,-0.055385,-0.296982,1
649,-0.746208,-0.811512,-0.072467,-0.101096,0.116699,-0.117976,-1.487735,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,-1.070639,1.128410,1.077252,-0.055385,-0.296982,1
650,-0.528271,1.724753,-0.072467,-0.302365,0.116699,-0.192786,-1.487735,-1.798693,1.814113,-0.055385,...,-0.078447,-0.055385,-1.182620,-0.111284,-1.070639,1.128410,1.077252,-0.055385,-0.296982,1
651,-1.147449,-0.919925,-0.653876,-0.503633,0.592050,-0.050209,0.671134,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,0.844285,-0.111284,-1.070639,-0.884846,-0.926866,-0.055385,-0.296982,1
652,0.295329,-0.289340,1.793381,-0.503633,-1.071677,-0.192977,0.671134,0.555108,-0.550389,-0.055385,...,-0.078447,-0.055385,-1.182620,-0.111284,-1.070639,-0.884846,1.077252,-0.055385,-0.296982,1

### crx part 3

In [63]:
np_crx_dummy=crx_dummy.to_numpy()
least_beta_crx=least_squares(np_crx_dummy,crx_dummy_label)
least_beta_crx
crxlabel_pred_least=[]
for i in range(0,len(crx_dummy_label)):
    crxlabel_pred_least.append(predict_value(least_beta_crx,crx_dummy.iloc[i]))

In [64]:
least_beta_crx

array([ 0.02390646, -0.02328253,  0.0467311 ,  0.07637193, -0.06883368,
        0.10023491, -0.00536199, -0.00542233,  0.28023846,  0.07648245,
       -0.30629792,  0.05023762,  0.07401004,  0.03139853,  0.05356556,
       -0.14589651,  0.00628455, -0.05802301, -0.00379269,  0.02222818,
        0.04892679, -0.01492523,  0.06890817,  0.11199272, -0.00086604,
        0.11222981,  0.04396796,  0.07724838,  0.05285175, -0.00786251,
        0.02750761, -0.02689778,  0.59739151,  0.10210667, -0.02234456,
       -0.01208696, -0.00446743, -0.09341501])

In [65]:
confusion_matrix(crxlabel_pred_least,list(crx_dummy_label))

array([[288,  16],
       [ 69, 280]], dtype=int64)

### crx part 4

### Voted

In [66]:
crxvote_pred=vote_perceptron(crx_dummy,crx_dummy_label)
confusion_matrix(crxvote_pred,list(crx_dummy_label))

array([[266, 176],
       [ 91, 120]], dtype=int64)

### Average

In [67]:
crxaverage_pred=average_perceptron(crx_dummy,crx_dummy_label)
confusion_matrix(crxaverage_pred,list(crx_dummy_label))

array([[259, 173],
       [ 98, 123]], dtype=int64)

### crx part 5

In [68]:
crxini_beta=[0]*38
crxini_beta[37]=sum(crx_dummy_label)
random.seed(6111016)
crxini_beta[random.randint(0,37)]=1

In [69]:
crxmini_beta = minimize_linear_classifier(crxini_beta,crx_dummy,crx_dummy_label)
crxlabel_pred_mini=[]
for i in range(0,len(crx_dummy_label)):
    crxlabel_pred_mini.append(predict_value(crxmini_beta,crx_dummy.iloc[i]))
confusion_matrix(crxlabel_pred_mini,list(crx_dummy_label))

array([[274, 109],
       [ 83, 187]], dtype=int64)

### crx part 6

In [70]:
crxslack_beta=slack_minimize_linear_classifier(200,crxini_beta,crx_dummy,crx_dummy_label)
crxlabel_pred_slack=[]
for i in range(0,len(crx_dummy_label)):
    crxlabel_pred_slack.append(predict_value(crxslack_beta,crx_dummy.iloc[i]))
confusion_matrix(crxlabel_pred_slack,list(crx_dummy_label))

array([[277, 113],
       [ 80, 183]], dtype=int64)

### crx part 7

In [71]:
crxmodel = SVC()
crxmodel.fit(crx_dummy,np.array(crx_dummy_label,dtype=int))
crxpredictions = crxmodel.predict(crx_dummy)
confusion_matrix(crxpredictions,np.array(crx_dummy_label,dtype=int))

array([[315,  17],
       [ 42, 279]], dtype=int64)